# Generated by Django 4.1.5 on 2023-02-03 15:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('open', 'open'), ('confirmed', 'confirmed'), ('completed', 'completed')], default='open', max_length=20)),
                ('destination', models.CharField(max_length=100)),
                ('arrival_time', models.DateTimeField()),
                ('passenger_number', models.IntegerField()),
                ('vehicle_type', models.CharField(blank=True, default='Car', max_length=50)),
                ('special_request', models.CharField(blank=True, max_length=100)),
                ('is_share', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL)),
                ('sharer', models.ManyToManyField(blank=True, related_name='sharer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
