# Generated by Django 4.1.5 on 2023-02-04 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0003_userex_remove_driver_driver_name_delete_userexten'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='special_features',
            new_name='special_info',
        ),
    ]
