# Generated by Django 4.1.5 on 2023-02-07 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0006_remove_ride_sharer_ride_sharers_ride_total_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='vehicle_required',
            field=models.CharField(blank=True, default='car', max_length=50),
        ),
        migrations.AlterField(
            model_name='ride',
            name='vehicle_type',
            field=models.CharField(blank=True, default='car', max_length=50),
        ),
    ]
